name: tdd_tutorial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  get: ^4.6.6
  http: ^1.2.1
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
